### PR TITLE
script: added seed-file

### PR DESCRIPTION
**Pull request by ceciliachung**

### CODE REVIEW

**Review by YuniceXiao — APPROVED** [review]

**Review by lrt98802 — COMMENTED** [review]
I saw that you are creating this file under `src`. Shall we create a separate folder for it?

**Comment by ulysseses** [comment]
@lrt98802 I'm fine with having it here or putting it in a folder like `seeds`. If we choose the former, we can always move it into a new `seeds` folder when we need to do so at a later time.

**Comment by ceciliachung** [comment]
I think the train of thought was that the seed scripts would be in the controllers folder, so it didnt make as much sense to have a seed folder with just the 1 file of the seed (unless we had the 3 seeds separately, but even then, since the scripts would be elsewhere, it would be extra folders)

**Comment by lrt98802** [comment]
I am fine with keeping it here as long as we move it together with the script in the future. Merging it now 😃

**Pull request merged**
